Enalean/tuleap-documentation-en

languages/en/developer-guide/dev-setup.rst
Added our commands and edits to install Docker on Fedora 21, including the DNS and firewall tweaks.
=> Add installing docker on Fedora 21

languages/en/administration-guide/howto.rst
The current reverse proxy configuration uses nginx default SSL/TLS parameters
which are vulnerable to the POODLE attack (CVE-2014-3566), proposes weak ciphers
and does not enable Perfect Forward Secrecy.
The proposed ciphers in this contribution are based on
the Mozilla's Server Side TLS Guidelines [1].
[1] https://wiki.mozilla.org/Security/Server_Side_TLS
=> Proposed reverse proxy configuration should not propose SSLv3

languages/en/administration-guide/backup.rst
I have juste rewritten the backup page to propose backup guidelines for administrators. We should not rely on the old backup cron anymore and let the user use its own backup tool.
=> Updating backup guide

languages/en/user-guide/rest/quick-start/query.rst
There is no REST route POST /trackers/:id/artifacts, only GET
=> Change curl -XPOST to curl -XGET

languages/en/administration-guide/project-export-import.rst
Document the <natures> node used to check artifact link types' existence on the target Tuleap platform
=> Document the <natures> node

Makefile
A lot of targets in the Makefile are not used, no need to keep unused dead
code. I just keep linkcheck as this is the only useful extra target that should
be more used (See #84).
=> Remove unused Makefile targets

languages/en/deployment-guide/intro.rst, languages/en/user-guide/pullrequest.rst
This contribution takes into account the changes made to the API in [gerrit #11648](https://gerrit.tuleap.net/#/c/tuleap/+/11648/).
This is part of [story #11477](https://tuleap.net/plugins/tracker/?aid=11477): have a dedicated references for pullrequests
=> Update PR documentation to acknowledge the presence of Git reference for each PR

Makefile, README.md, requirements-dev.txt, requirements.txt
This patch introduces the watch mode for the documentation.
How to test:
--------------
source venv/bin/activate
make SPHINXOPTS="-D html_theme=tuleap_org" watch-html
1. A web server starts in watch mode.
2. The doc is partially rebuilt each time you save your work
3. The browser is refreshed with your last changes
=> issue #62 Add watch target in Makefile

languages/en/_themes/tuleap_org/header.html
Some links were missing:
- link to Use cases
- link to Online trainings
=> Add missing links in the Resources menu

languages/en/installation-guide/full-installation.rst
Even if the tuleap package will be installed by dependency of a plugin, it may be clearer to install it explicitly.
=> Make package installation clearer

languages/en/admin.rst, languages/en/administration-guide/admin-tasks.rst, languages/en/administration-guide/customisations.rst, languages/en/administration-guide/projects-management.rst, languages/en/administration-guide/projects-management/project-export-import.rst, languages/en/administration-guide/projects-management/project-status.rst, languages/en/administration-guide/projects-management/project-website.rst, languages/en/administration-guide/projects-management/projects-settings.rst
In order to better organize administration guide, I suggested in
fe0b81ce1abdac0481b69aac0ce4295e5189dddf to have Projects management,
Users management, … sections.
This commit move some existing content in Projects management section.
=> Move projects management doc in Projects management section

languages/en/administration-guide/system-administration/backup.rst
When rendered in Sphinx , copy/paste from the Backup/Restore documentation is not working for this command as the double hyphens are misrendered.
`/usr/lib/forgeupgrade/bin/forgeupgrade --config=/etc/tuleap/forgeupgrade/config.ini update`
This pull request fixes that little issue.
=> Fix for Sphinx rendering in backup documentation

languages/en/deploy.rst, languages/en/deployment-guide/deprecations.rst
This page will list all planned deprecations but also planned versions
support. It should help platform administrators anticipate future
deployments and share a vision of which technologies will be dropped and
when.
=> Add "Deprecations" page

languages/en/user-guide/project-admin.rst
Add a table in Service configuration to list the special Service label
and description keys. Those keys, if left as-is are then translated.
It helps to have this table in case the siteadmin has customised one of
these services' label or description. They can go look that table and
paste the correct key to get translated labels again.
=> Add Service special label and description keys

languages/en/developer-guide/quick-start/run-tuleap.rst
As part of https://tuleap.net/plugins/tracker/?aid=13775, most of our dev dependencies have dropped support for Nodejs v6.
As you can see on https://nodejs.org/en/about/releases/, Nodejs v6 has reached its end of life and is no longer maintained.
=> Increase minimum required nodejs version to v8

languages/en/developer-guide/front-end.rst, languages/en/developer-guide/front-end/jest.rst, languages/en/developer-guide/front-end/karma.rst
Part of request #13806: Use Jest as the default test framework for JS unit tests
=> Add a page about Jest in the front end dev guide

languages/en/developer-guide/front-end/vue.rst
- Disallow conditional translations without `key` attributes
- Disallow interpolation in translated strings
- Disallow v-bind in translated strings
=> Add rules about gettext translations in Vue

languages/en/developer-guide/front-end/vue.rst
Also reworded the rule about unneeded computed properties.
=> Revert to snake_case for Vue.js props

languages/en/user-guide/troubleshooting.rst
Taskboard is the first Tuleap application to decline its access to IE11 users. We should not encourage users to use Tuleap with a browser from the past.
=> Update browser compatibility list

languages/en/deployment-guide/intro.rst
We should warn administrators that some .tab entries has been remove since it can have impact in the footer if it has been customized.
=> Removal of copyright and powered_by .tab entries

languages/en/_themes/tuleap_org/index.html, languages/en/_themes/tuleap_org/style/_doc.scss
Out of the 5 hardcoded links that has been put in this section:
* 3 are about things that only concern Tuleap contributors (i.e. probably not the
most popular content)
* 1 is broken
In the current state not having this section at all probably brings the same value.
=> Remove the "popular" links on the index page of tuleap_org theme

languages/en/_themes/tuleap_org/layout.html, languages/en/_themes/tuleap_org/static/documentation_options.js_t
The documentation options are now loaded via a dedicated script like in
the Sphinx basic theme [0].
[0] https://github.com/sphinx-doc/sphinx/blob/v3.0.0/sphinx/themes/basic/layout.html#L90
=> Search result links are broken when the docs.tuleap.org theme is used

languages/en/developer-guide/back-end/widgets.rst, languages/en/developer-guide/front-end/css.rst, languages/en/developer-guide/front-end/javascript.rst
Following https://tuleap.net/plugins/tracker/?aid=14752, Tuleap Core
follows the same structure as plugins where webpack.common.js is at the
root of src/ and builds both scripts and themes.
The dev guide has been updated to reflect that.
=> Adapt paths to core build unification

languages/en/administration-guide/system-administration/advanced-deployments.rst, languages/en/deployment-guide/11.x.rst
Also removed all direct installations of the extension since it is now a
dependency of the main Tuleap package.
=> Mention migration to PHPRedis 5 in the migration guide

languages/en/user-guide/code-versioning/git.rst
Part of request #14127: Extend markdown support in the git plugin
https://tuleap.net/plugins/tracker/?aid=14127
=> Mention that Markdown document can be rendered in the Git web UI

languages/en/deployment-guide/11.x.rst
The Test Plan plugin should be installed if the integration was used.
Part of story #14882: Create new campaign in new “Test” screen
=> Mention explicitely that TTM tab in the agile dashboard is gone

languages/en/administration-guide/system-administration/backend-workers.rst
This commit adds a list of what is not imported during a Jira tracker import.
Please let me know if some things have been omitted.
=> [Jira import] List what's not part of the import yet

languages/en/installation-guide/import.rst
We don't need it anymore since we now have native support for Jira trackers import.
=> Remove mention of Jira in tjhe [Import from other tools] section

languages/en/developer-guide/front-end.rst
Typo error in Front end documentation: "vanilia JS" --> "vanilla JS".
=> Fix typo in Front end documentation

languages/en/user-guide/integration/rocketchat.rst
Adding some precision on which server to apply the configuration as it was not clear.
=> Adding precision for rocket.chat integration

package-lock.json, package.json, webpack.common.js, webpack.dev.js, webpack.prod.js
While Webpack 5 is still in RC, it should be stable enough to be used on
a non critical project. It also allow us to have a glance of what the
migration to Webpack 5 will look on the main Tuleap repo.
The optimize-css-assets-webpack-plugin plugin has been replaced with the
css-minimizer-webpack-plugin plugin: it already supports Webpack 5
without warning and  it seems to be the most recommended option nowadays
(it is maintained under the webpack-contrib namespace).
The webpack-fix-style-only-entries plugin has been removed has been
removed for now. It throws deprecation warnings when used with Webpack 5
and is not really critical in this repository.
=> Move the docs.tuleap.org theme to Webpack 5

languages/en/deployment-guide/12.x.rst
[request #16681](https://tuleap.net/plugins/tracker/?aid=16681): OIDC accounts must use SVN tokens
=> Add instructions in the deployment guide to give access to plugin_openidconnectclient_user_mapping to dbauthuser

languages/en/deploy.rst
Gerrit 3.3 release is planned for [November 9](https://www.gerritcodereview.com/2020-09-07-gerrit-3.3-release-plan.html) meaning that Gerrit 3.0 will be EOLed upstream.
=> Adding Gerrit 3.0 to the list of end of support for S2 2020

languages/en/installation-guide/ansible-installation.rst
I updated the ansible role to install Tuleap, and the documentation needs a refresh
=> Renew ansible-tuleap documentation

docs.tuleap.org/nginx.conf
This change is the equivalent on docs.tuleap.org of git #tuleap/stable/7971b7c35005d428fe3109955744c81fee3e999a.
=> request #17114: Setup cross-origin isolation when loading the documentation

languages/en/administration-guide/application-management/motd.rst, languages/en/deployment-guide/12.x.rst
MOTD files are not supported anymore.
Part of [story #14670](https://tuleap.net/plugins/tracker/?aid=14670): display a site wide banner (motd)
=> Platform banner is defined through the web interface

languages/en/administration-guide/users-management/security/permissions-overrider.rst, languages/en/deploy.rst, languages/en/deployment-guide/12.x.rst
Take the opportunity to re-organize the deprecation tables
at it was out-dated and messy.
I removed the start of support because it's hard to commit
on dates and may let people think that we met the deadlines...
=> Announce deprecation of PermissionsOverrider

languages/en/user-guide/code-versioning/gitlab.rst
In the section `Prerequisites` the list should be displayed with bullets
and line returns
=> List badly formatted in plugin-gitlab documentation

.github/workflows/CI.yml
Run on Ubuntu 20.04 instead of 18.04 and check that the documentation can be built on Python 3.9.
=> Update CI pipelines

languages/en/administration-guide/projects-management/export-import/import-format/trackers.rst
For now, only Step defintion is descibe as external field on documentation. Step execution must be add.
=> Add Step Execution as external field

languages/en/administration-guide/system-administration/backend-workers.rst, languages/en/deployment-guide/12.x.rst
Part of [request #19219](https://tuleap.net/plugins/tracker/?aid=19219): Creating a new tracker from a Jira import might not be available even when the instance can do background processing
=> Remove sys_async_mails setting

languages/en/user-guide/trackers/administration/configuration/semantics.rst
Some documentation was missing on the Timeframe semantic.
Also, the Progress semantic has been released in Tuleap 12.8, so let's introduce it!
=> Add documentation on semantics Timeframe and Progress

languages/en/installation-guide/install-plugins.rst, languages/en/installation-guide/update.rst
Part of [request #18496](https://tuleap.net/plugins/tracker/?aid=18496): Move nginx & apache configuration deployment to tuleap-cfg site-deploy
=> Calling /usr/share/tuleap/tools/utils/php73/run.php is no more useful

package-lock.json
No security impact on the build as we do not use PostCSS.
=> Fix CVE-2021-23368 of postcss dependency

languages/en/developer-guide/back-end/events.rst, languages/en/developer-guide/front-end/mustache.rst
Part of [request #20938](https://tuleap.net/plugins/tracker/?aid=20938): Add support of PHP 7.4
=> Use PHP 7.4 typed properties in code examples

languages/en/user-guide/code-versioning/gitlab.rst
This is part of story #17181 reference tuleap artifacts in gitlab branches
=> [doc] Add documentation about GitLab branch references

default.nix, docs.tuleap.org/Dockerfile, pinned-nixpkgs.nix, shell.nix
This makes sure the build is consistent and avoid surprises between different tool versions. Also, this way there is only one tool list to maintain.
=> Build docs.tuleap.org using the same tools than developers

languages/en/user-guide/trackers/administration/configuration/semantics.rst
part of: [story #21362](https://tuleap.net/plugins/tracker/?aid=21362) - Base artifact timeframe on a linked artifact
=> Update semantic timeframe documentation

languages/en/deployment-guide/12.x.rst
This is part of story #21386: dry run REST project creation
=> Project creation has been removed from SOAP API

languages/en/_themes/tuleap_org/style/backbone/_basic-elements.scss
The download links are shown as inlined code, this contribution makes them render as standard links with a download icon first (like it is the case on the RTD theme).
=> Fix the apparence of the download links on the docs.tuleap.org theme

languages/en/developer-guide/front-end/internal-libs.rst
Some changes have been recently and the current document is outdated.
[request #22680](https://tuleap.net/plugins/tracker/?aid=22680): Manage typechecking and .d.ts generation with Vite plugins
[request #22693](https://tuleap.net/plugins/tracker/?aid=22693): Typecheck the template of the vue-breadcrumb-privacy library
=> Update the dev guide for authoring internal frontend libs

.github/workflows/CI.yml, Dockerfile-linkcheck, Jenkinsfile-linkcheck, linkcheck-docker.nix
We now use [buildkit-nix](https://github.com/AkihiroSuda/buildkit-nix/) to directly build the image
=> Fix the build of the linkcheck Docker image

languages/en/installation-guide/import.rst
The repository has been deleted by its original maintainer.
A copy can be found in the Software Heritage project archive if needed:
https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/jpo38/TrackerIO
=> Drop Redmine import section using TrackerIO

languages/en/developer-guide/quick-start/run-tuleap.rst
Skipping forgeupgrade is not needed anymore on macOS environments.
=> Remove unneeded macOS specificities related to forgeupgrade

.gitpod.Dockerfile, .gitpod.yml
This way we do not need to pull them each time we open the workspace but only once when we build the image (note that we could pre-build them).
Also removed the tools that were downloaded from a unpinned nixpkgs.
=> Add dev tools to the Nix store when building the Gitpod image

.gitpod.yml, .vscode/settings.json
This is not strictly required but at this time it's an automatic workaround
for the typing issues (shortcuts, enter, etc) that are not well supported
with restructured text & gitpod
=> Add python extension

languages/en/deploy.rst
There were three different times for Gerrit < 3.1 support. Two of them
had to be wrong, so I kept the date furthest away (December).
=> Remove redundant mentions of Gerrit support

languages/en/_themes/tuleap_org/style/backbone/_basic-elements.scss, languages/en/administration-guide/system-administration/customisations.rst, languages/en/deployment-guide/13.x.rst, languages/en/developer-guide/i18n/vue.rst, languages/en/developer-guide/internationalization.rst, languages/en/developer-guide/patches.rst
* Inform existing instances that a new language is available
* Mark customized localization (aka .tab) as deprecated
* Add more context to contributors about gettext translation in Tuleap
* Inform developers how to add a new language
* Replace one-item lists by titles for better readability in i18n/vue
Part of [request #26745][1]: Add Brazilian Portuguese contribution
[1]: https://tuleap.net/plugins/tracker/?aid=26745
=> Please welcome pt_BR 🎉

languages/en/user-guide/documents-and-files/document.rst, languages/en/user-guide/tuleap-entreprise.rst
We should remove the warning at the top of the dedicated documentation
and remove it from the list of Tuleap Enterprise plugins.
Part of [story #26808: have document part of Community Edition][0]
[0]: https://tuleap.net/plugins/tracker/?aid=26808
=> Document is now part of Tuleap Community Edition

languages/en/_themes/tuleap_org/static/documentation_options.js_t, languages/en/administration-guide/users-management/security/dynamic-credentials.rst
The context of search results is displayed (or not) depending on a conf setting in recent versions of Sphinx.
=> Add back context in search results when using the tuleap.org theme

languages/en/user-guide/ci.rst
`tuleap-api-plugin` for Jenkins is about to be updated to version `2.289.3` of Jenkins.
=> Update minimal Jenkins requirement

languages/en/_themes/tuleap_org/style/backbone/_header.scss
It avoids the annoyance of opening a link and not seeing what the section is.
Note that the `scroll-margin-top` is always set even when the `.pinned` class is not set on the `body`. The `.pinned` class is set via a JS script so the browser is likely to have already scroll to the section before the class is set (and so the section would end up under the header).
=> Prevent anchor section links to go under the header on tuleap.org theme

languages/en/deployment-guide/13.x.rst
Part of request #26407: De-duplicate authz/authn code used for SVN accesses
=> Mention the changes related to the SVN auth in Tuleap 13.11 deployment guide

languages/en/user-guide/code-versioning/git.rst
Part of [request #27906](https://tuleap.net/plugins/tracker/?aid=27906): Token is required when using `notifyCommit` webhook endpoint
=> Update Jenkins webhook section to mention Jenkins notifyCommit access tokens

languages/en/administration-guide/application-management/plugins/trackers.rst, languages/en/administration-guide/system-administration/email-relay.rst, languages/en/administration-guide/system-administration/services.rst, languages/en/installation-guide/docker-image.rst, languages/en/installation-guide/full-installation.rst
This is part of story #27133 send mail without postfix
Add a new section in System administration to explain how to configure
the email relay.
Some modifications are done in other part of the documentation to
reflects this new configuration.
=> doc: Add documentation for email relay

languages/en/user-guide/integration/rest/api.rst, languages/en/user-guide/integration/rest/tus.rst
There are 3 requests needed to achieve that. The last one especially was
not documented, there was no way to know the shape of the payload
expected to attach a file to an artifact.
Note that I could not test properly this script, I did not set up a
bundler/compiler for that.
=> Add an example of how to attach a file to an Artifact with TUS

languages/en/administration-guide/projects-management/export-import/project-import.rst
We must use the root user to be able to create a new project.
If we give to the tool the user that must be the project admin, the ProjectXMLImporter try to remove him from the members of the project. This is not what we expect.
=> Specifies import of a non existing project

languages/en/user-guide/misc.rst
[request #29218](https://tuleap.net/plugins/tracker/?aid=29218): Show a deprecation message to users using Firefox < 91 or Chrome < 93
=> Raise "best effort" browser support

.github/workflows/CI.yml
The other builds done with a Python provided by the GHA actions/setup-python will be removed at the same time than the requirements.txt/requirements-dev.txt.
=> Add a CI steps building the doc using the Python provided by the Nix environment

languages/en/administration-guide/application-management/plugins/full-text-search.rst, languages/en/deployment-guide/14.x.rst
Closes request #29633: Meilisearch: 0.29.2 -> 0.30.0
=> Adding upgrade instruction for Meilisearch 0.30.0

languages/en/developer-guide/front-end/internal-libs.rst, languages/en/developer-guide/front-end/vue.rst
Our documentation should use the "workspace" protocol in examples.
part of [request #29637](https://tuleap.net/plugins/tracker/?aid=29637) Link packages through `workspace:` protocol
=> Document "workspace" protocol for dependencies

languages/en/installation-guide/full-installation.rst
People usually copy/paste things when they install. It makes more sense to list the more commonly used packages
instead to have a restricted list of packages.
=> More complete install by default

languages/en/administration-guide/projects-management.rst, languages/en/administration-guide/projects-management/project-website.rst
Deploying this is basically not really possible anymore. Keeping the information in the documentation is more confusing than anything else.
=> Drop last reference of `Project Website`

languages/en/developer-guide/release.rst
All plugins and tools that are package are in the main Tuleap repository.
Part of [request #30743](https://tuleap.net/plugins/tracker/?aid=30743): Merge external plugin repositories into the main repository
=> Remove information about the release process of "external" plugins

languages/en/developer-guide/back-end/flowcharts.rst
When users are invited into a project, they are not redirected to my, they are redirected to project dashboard.
Part of [story #30021][0]: Invite buddies to my Tuleap project
[0]: https://tuleap.net/plugins/tracker/?aid=30021
=> Complement user registration flowchart for project invitation

.github/workflows/CI.yml, build-support/build-tools.nix, languages/en/conf.py, requirements-dev.txt, requirements.txt
It gets blocked by our CSPs anyway and outside the security concern of loading a non pinned script this is unlikely to be legal under European laws.
Took the easiest way here and the graphs are now generated during the build. It also avoid loading 800KB+ of JS on every page.
=> Do not load mermaid script from an external server

languages/en/deployment-guide/14.x.rst
Part of [request #30751](https://tuleap.net/plugins/tracker/?aid=30751): Meilisearch: 0.30.5 -> 1.0.0
=> Add info about the 1.0.0 upgrade of the local Meilisearch server

languages/en/deployment-guide/14.x.rst
Deployment guide must remove "under development" section for 14.6
=> Tuleap 14.6 is released

languages/en/installation-guide/docker-image.rst
It seems this was only needed for the "single server" and the documentation pages related to the "single server" seems to have been removed.
This should make `make linkcheck` happy again.
=> Drop info about the specific Azure DB suffix

languages/en/deployment-guide/14.x.rst
A bit was missing in the public documentation : 
You have to restart tuleap-meilisearch before re-indexing your data.
=> Added doc on meilisearch upgrade

languages/en/deployment-guide/14.x.rst, languages/en/user-guide/misc.rst
Part of request #31952: Move build targets to current Firefox ESR
=> Set browser build target to Firefox 102

languages/en/user-guide/tql-artlink.rst, languages/en/user-guide/tql.rst
Part of [story #32281][0]: Search artifacts with/without parents via TQL
[0]: https://tuleap.net/plugins/tracker/?aid=32281
=> Document WITH/WITHOUT PARENT syntax for TQL

languages/en/user-guide/tql-artlink.rst
Part of [story #32307][0]: Search artifacts with/without children via TQL
[0]: https://tuleap.net/plugins/tracker/?aid=32307
=> Document WITH/WITHOUT CHILDREN syntax for TQL

languages/en/user-guide/tql-artlink.rst, languages/en/user-guide/tql.rst
It started to be a mess with all those nested lists, so they are replaced by chapters.
Part of story #32309: Search artifacts with/without links via TQL
=> Document IS (NOT) LINKED TO

build-support/pinned-nixpkgs.nix
Part of request #33604: Update dev/build environment [W30 2023]
=> Use the same nixpkgs pin than Tuleap main repo

languages/en/user-guide/agile-dashboard.rst, languages/en/user-guide/kanban.rst, languages/en/user.rst
Kanban will soon be a whole service, outside of Agile Dashboard. It deserves its own documentation.
Since the legacy is the default behavior, screenshots and documentation content are kept as is until the split becomes the default.
Part of [story #33646][0]: access Kanban in a dedicated service
[0]: https://tuleap.net/plugins/tracker/?aid=33646
=> Extract kanban documentation

languages/en/user-guide/trackers/usage/move-artifact.rst
The big "Note" was harder to read, the list inside it was not rendered properly. Fixed a syntax problem with the system types (this is ReStructuredText, not Markdown).
Also added a proper image description to the screenshot.
=> Improve readability of the "move artifact" section

languages/en/user-guide/backlog.rst
Usage should be explained before the creation
Note: only chapters are moved, content is kept as is for now.
Part of [story #33979][0]: have dedicated Backlog service
[0]: https://tuleap.net/plugins/tracker/?aid=33979
=> move usage of backlog at the top

languages/en/deployment-guide/15.x.rst
MediaWiki 1.35 was the last user of PHP 7.4 packages. They are not more needed anymore.
Part of [story #35103](https://tuleap.net/plugins/tracker/?aid=35103): upgrade to MediaWiki 1.39
=> Removal of PHP 7.4 dependencies

languages/en/installation-guide/step-by-step/upgrade.rst
The Upgrade documentation as it stands today uses yum instead of dnf.  
As we have sent CentOS into legacy mode, we should use DNF instead.
=> Upgrade documentation should use dnf

languages/en/deployment-guide/15.x.rst, languages/en/installation-guide/step-by-step/redis-configuration.rst
The configuration variable `$sys_nb_backend_workers` is now set via the command `tuleap config-set sys_nb_backend_workers 2`.
Part of [story #35093][0]: execute custom code as artifact post action
[0]: https://tuleap.net/plugins/tracker/?aid=35093
=> $sys_nb_backend_workers removed from local.inc

languages/en/deployment-guide/15.x.rst
Part of request #30344: Run Tuleap with PHP 8.2
=> chore: PHP 8.1 packages can be removed

languages/en/installation-guide/docker/docker_compose.rst
During my last refactor, we decided to throw Mailhog out of the stack.  
I obviously forgot to remove the dependance for Tuleap's container.  
Thanks TCottier for the information !
=> fix: Compose file should not have mailhog references

languages/en/deployment-guide/15.x.rst, languages/en/installation-guide/step-by-step/install-plugins.rst, languages/en/user-guide/tuleap-entreprise.rst
Take the opportunity to clarify a bit the installation process
=> Document installation of Tracker Functions plugin

languages/en/administration-guide/system-administration/monitoring-with-prometheus.rst, languages/en/installation-guide/step-by-step/redis-configuration.rst, languages/en/user-guide/trackers/administration/tracker-creation.rst
The only remaining direct usage of Redis is for the monitoring parts. Async event queue is backed by the DB by default now.
Part of request #37566: Support the async event queue using the DB instead of Redis
=> feat: Remove mention of backend workers with Redis

languages/en/installation-guide/docker/docker_compose.rst, languages/en/installation-guide/docker/images-configuration.rst, languages/en/installation-guide/step-by-step/redis-configuration.rst
The only remaining usage of Redis in Tuleap is for the prometheus_metrics plugin is only usable with TEE.
Part of request #37566: Support the async event queue using the DB instead of Redis
=> chore: Remove mention of Redis in TCE Docker deployment

build-support/pinned-nixpkgs.nix
Use the same pin than for Tuleap main repo.
Part of request #37907 Update dev/build environment [W17 2024]
=> chore: Update nixpkgs pin

languages/en/installation-guide/docker/docker_compose.rst
The `version` key is deprecated in recent version of Docker Compose.
=> Docker compose version key drop

languages/en/deployment-guide/15.x.rst
Part of story #38263 Choose my own columns based on field name (numeric, text, dates)
=> docs: Document cross-tracker search API breaking change

languages/en/conf.py
This commit fix the links for install-packages-tce and install-packages-tee.
=> Fix: Redirection links for new page install packages

languages/en/installation-guide/step-by-step/install-packages.rst
The old ones still work but it is preferable to use this one on new setups.
Part of enalean_internal #106659
=> chore: Update direct URLs to TEE RPM repo

languages/en/installation-guide/step-by-step/install-packages.rst
This might not be obvious to everybody.
=> fix: mention where the repo configuration is supposed to go

languages/en/installation-guide/step-by-step/install-packages.rst, languages/en/installation-guide/step-by-step/install-plugins.rst, languages/en/user-guide/documents-and-files.rst, languages/en/user-guide/documents-and-files/artidoc.rst, languages/en/user-guide/documents-and-files/doc.rst
Now that artidoc is not anymore an experimental plugin, we can start to document it.
Part of [story #38288](https://tuleap.net/plugins/tracker/?aid=38288): add a new section
=> Initiate artidoc documentation

Jenkinsfile-build-docs.tuleap.org
Part of some internal work art #108457
=> chore: Stop deploying docs.tuleap.org in the build image pipeline

languages/en/deployment-guide/15.x.rst
Part of request #39012 Installation might not succeed when a long domain name is used
=> fix: Existing nginx directive `server_names_hash_bucket_size` must be removed

languages/en/deployment-guide/15.x.rst
Part of request #39025 Meilisearch: 1.7.6 -> 1.9.0
=> Add info about Meilisearch 1.9.0 upgrade in the deploiement guide

languages/en/deploy.rst, languages/en/deployment-guide/15.x.rst, languages/en/deployment-guide/16.x.rst
Start the development of Tuleap 16.0
Since it is the beginning of a new release cycle, I've added the file `deployment-guide/16.x.rst`.
=> Start development of 16.0

.gitignore, .vscode/settings.json, languages/en/_pygments/lexer.py, languages/en/_pygments/tuleap_style.py, languages/en/conf.py, languages/en/user-guide/tql.rst
It allow to have syntax highlight for TQL code blocks
=> feat: Add pygments lexer for TQL

languages/en/_themes/tuleap_org/style/_backbone.scss, languages/en/_themes/tuleap_org/style/_doc.scss, languages/en/_themes/tuleap_org/style/_fonts.scss, languages/en/_themes/tuleap_org/style/_reset.scss, languages/en/_themes/tuleap_org/style/backbone/_badge.scss, languages/en/_themes/tuleap_org/style/backbone/_basic-elements.scss, languages/en/_themes/tuleap_org/style/backbone/_card.scss, languages/en/_themes/tuleap_org/style/backbone/_footer.scss, languages/en/_themes/tuleap_org/style/backbone/_form.scss, languages/en/_themes/tuleap_org/style/backbone/_header.scss, languages/en/_themes/tuleap_org/style/main.scss, package.json, vite.config.ts
Implements request #39744 Bring up to date docs SCSS styles
The "tuleap-org" theme styles should not be more broken than before :p.
No style change expected.
Why?
1. vite now uses the "modern" API for sass, the legacy JS API is
deprecated
2. vite now uses the NodePackageImporter, enabling `pkg:` imports
3. The styles now use `@use` instead of `@import`, which is deprecated (and
has weird scoping)
4. The styles no longer use deprecated functions such as
transparentize(), lighten() and darken()
=> chore: replace deprecated sass functions and imports

Makefile, languages/en/administration-guide/system-administration/backup.rst, languages/en/installation-guide/docker/docker_compose.rst, languages/en/installation-guide/docker/images-configuration.rst
- update main tuleap data directories
- add "tip" for usermapping when restoring with rsync
- add "tip" for external disk storage (with symbolic links or bind-mount with fstab)
- add links from docker install guide
- rename/fix compose service name and setup output (web -> tuleap)
- fix typo in Makefile
- fix `make clean` command to not remove the tmp directory itself that is part of the repo files
=> doc: review tuleap backup and add tips

languages/en/user-guide/tql/cross-tracker-search.rst
Part of [story #40088 Expert mode is the new default for cross tracker search](https://tuleap.net/plugins/tracker/?aid=40088)
=> Add the mention of MY_PROJECTS() in TQL Cross-Tracker Search doc

languages/en/user-guide/integration/webhook.rst
Part of [request #41465](https://tuleap.net/plugins/tracker/?aid=41465) Expose a `submitter_user_groups` key in the artifact update webhook payload
=> feat: Update artifact webhook payloads to include `submitter_user_groups`

languages/en/administration-guide/projects-management/export-import/import-from-other-tools.rst
Part of request #41477 Stop publishing enalean/bz2tuleap image on Docker Hub
=> fix: Update link to bz2tuleap container image

languages/en/administration-guide/system-administration/services.rst
Why?
The LDAP write feature for Tuleap has been removed in June of 2023. We should remove mention of it in the user docs.
The ability to write plugin configuration in the siteadmin web UI has also been removed (I don't know when, sometime ago), we should point the user to the config file (although work is ongoing to replace it).
I changed the headings styles to match Sphinx docs convention [1]. I find that it avoids breaking my editor's syntax highlighting, like backticks do.
I also switched from "ldap" to "LDAP" because it's the more usual spelling (it is after all an acronym).
[0] https://tuleap.net/plugins/git/tuleap/tuleap/stable?a=blob&hb=5803f5b0eddfc4fd1eb4662dac7448db225366cc&f=docs%2Fdecisions%2F0024-remove-ldap-write.md
[1] …
=> docs: Remove outdated info from LDAP docs

.github/renovate.json, .github/workflows/CI.yml
This should prevent Renovate to try to use the latest main commit.
https://docs.renovatebot.com/modules/manager/github-actions/#digest-pinning-and-updating
Follow up to #1628
=> chore: Specify version of GitHub Actions

.github/renovate.json
Updating all the transitives deps at once is probably not a good thing in our context as it could be harder to determine the source of an issue.
=> chore: Disable Renovate lockfile maintainance

Jenkinsfile-build-docs.tuleap.org
This is needed due to changes on Enalean infrastructure.
Similar to request #42985
=> fix: Fix the publication of the container image of docs.tuleap.org

languages/en/_themes/tuleap_org/layout.html, languages/en/_themes/tuleap_org/static/documentation_options.js_t
This fixes the search on the Tuleap theme, the extract of the content of the search results is not visible since the upgrade to Sphinx 7.2.
=> fix: Search "extracts" are shown when the Tuleap is used

languages/en/deployment-guide/16.x.rst
Part of [request #43700](https://tuleap.net/plugins/tracker/?aid=43700) Drop support of PHP 8.2
=> chore: Add the cleanup of PHP 8.2 packages in the deployment guide
