Enalean/tuleap-documentation-en

- languages/en/administration-guide/project-export-import.rst
Add a section to describe FRS import syntax
> Describe FRS import syntax

- languages/en/administration-guide/project-export-import.rst
Clarify which processors and file types can be used
Generated using:
select group_concat(concat(' ``', name, '``')) from frs_filetype;
select group_concat(concat(' ``', name, '``')) from frs_processor;
> Add a list of processors and filetypes as found on a fresh tuleap instance

- languages/en/administration-guide/project-export-import.rst
Should be merged once https://gerrit.tuleap.net/#/c/5199/ is merged.
> Complete the mediawiki plugin data import documentation.

- languages/en/administration-guide/project-export-import.rst
This should allow better navigtion in http://tuleap-documentation.readthedocs.org/en/latest/administration-guide/project-export-import.html
> Rework import format heading levels

- languages/en/user-guide/tql.rst
All dynamic user groups are now supported in TQL
> Remove limitation for user groups in TQL

- .gitignore
- languages/en/deployment-guide/intro.rst
In addition, update the .gitignore to exclude by default the venv folder
> Add info about crosstracker in deployement guide

- languages/en/developer-guide/quick-start/install-docker.rst
* Fixed broken links
* Install instructions updated for Fedora 24+ using dnf
> Update Docker install for Linux distributions.

- languages/en/installation-guide/update.rst
Also mention that users probably want to read the deployment guide
before upgrading.
> Update upgrade instructions to take into account nginx

- languages/en/deployment-guide/intro.rst
This is part of request #10815 Each access to a report log information not needed
> Inform about debug.log deletion

- languages/en/installation-guide/advanced-configuration.rst
This is part of request #11028 Update Webdav README
> Add webdav configuration in documentation

- languages/en/user-guide/tracker.rst
This is part of story #10325 search in artifact comments from classic view
> Add documentation about Tracker report classic search with comments

- languages/en/deployment-guide/intro.rst
"change" makes people think the parameters should already be present.
I also added to restart mailman to better match plugin_forumml/README.mkd
> Explain that mailman params are to be added

- languages/en/administration-guide/backup.rst
We need to stop nginx during the backup process.
> Stop nginx during backup

- languages/en/developer-guide/coding-standards.rst
This is part of [request #11256](https://tuleap.net/plugins/tracker/?aid=11256): Deprecate usage of the \DataAccessObject class and db_* functions
> Prepared statements should be the way to query the database

- languages/en/deployment-guide/intro.rst
- languages/en/installation-guide/advanced-configuration.rst
This is part of https://tuleap.net/plugins/tracker/?aid=9007
> IE compatibility header is now provided by Tuleap

- requirements.txt
No functional changes is expected.
> Upgrade to Sphinx 1.7.2

- languages/en/user-guide/tql.rst
- Add detail on supported comparisons
- Explicit supported ``@`` keywords, what they represent and how they behave.
- Detail preconditions for using a semantic or always-there field in cross-tracker search
- Detail possible values for cross-tracker search
> Update cross-tracker TQL documentation

- languages/en/developer-guide/coding-standards.rst
So that newcomers expect that javascript code is parsed and formatted by
these tools.
> Add an explanation of eslint and prettier for coding standards

- languages/en/user-guide/tracker.rst
- languages/en/user-guide/webhook.rst
This is part of story #11035 trigger webhook on artifact update
> Document new tracker webhooks

- languages/en/_themes/tuleap_org/layout.html
We need title guide (developer, user, deployment…) as class on the body tag so each guide has its own color 🌈
> Add the title guide as class on the body tag

- languages/en/developer-guide/back-end/tests.rst
This is part of story #11410 use last simpletest stable version
In addition, very first mentions of PHPUnit is added.
> Remove backend test section about test UI.

- languages/en/deployment-guide/intro.rst
This is part of story #12345 export results to csv
> The custom file for xTracker plugin must be deleted

- languages/en/developer-guide/back-end.rst
- languages/en/developer-guide/back-end/redis.rst
This is the second time in less than one month that I have to disturb my
teammates in order to be able to use Redis in my dev environment. I suggest to
write down my notes here so that everyone can benefit from my failures.
> Explain how to use redis in dev environment

- languages/en/developer-guide/coding-standards.rst
- languages/en/developer-guide/front-end/javascript.rst
- languages/en/developer-guide/front-end/vue.rst
To help keep consistent naming schemes.
> Add Vue.js best practices for Tuleap

- languages/en/developer-guide/patches.rst
Reverts Enalean/tuleap-documentation-en#136
> Revert "Adapt git push commands to new Gerrit topics"

- languages/en/developer-guide/back-end/tests.rst
> Fix rest tests commands

- languages/en/installation-guide/install-plugins.rst
Alternative way to activate plugin
for more info check Tuleap-devel discussion :
https://tuleap.net/pipermail/tuleap-devel/2019-January/005951.html
> Add doc: how to activate plugin from cmdline

- languages/en/administration-guide/customisations.rst
- languages/en/administration-guide/run-php56.rst
- languages/en/user-guide/project-website.rst
Add missing warnings for deprecated feature "Project web sites"
> Add warnings for deprecated project web sites

- languages/en/administration-guide/customisations.rst
- languages/en/developer-guide/back-end/gettext.rst
Explain how to clear cache for translations
> Explain cache clear for translations

- languages/en/user-guide/tracker.rst
This is part of story #12187 configure workflow pre & post actions at target state level
> Add documentation about workflow simple mode

- languages/en/administration-guide/projects-management/project-export-import.rst
This is part of story #13243 Import/export workflow simple mode via XML
> Document the simple workflow XML format

- languages/en/user-guide/rest/api.rst
Now we no longer need to bother with base64 encoding. I also show how to
find a file field and where the html_url comes from in a file field
value.
> Update "Retrieve artifact attachment" snippet

- languages/en/deployment-guide/intro.rst
To be merged with [gerrit #15705](https://gerrit.tuleap.net/c/tuleap/+/15705)
> request #13726: Cleanup information given by the docman plugin in the REST endpoint GET /project/:id

- languages/en/user-guide/code-review/pullrequest.rst
It makes things easier to configure especially in a pipeline.
> Mention CS-SI/tuleap-jenkins-lib library to configure feedbacks on PR

- package-lock.json
npm audit should report 0 vulnerabilities
> Upgrade minimist and kind-of versions

- languages/en/user-guide/code-versioning/svn-plugin.rst
- languages/en/user-guide/code-versioning/svn.rst
All predefined permissions can be overloaded.
> request #14834 Erroneous restriction on SVN permissions

- languages/en/deployment-guide/11.x.rst
- languages/en/installation-guide/install-plugins.rst
Part of story #14881: Transform “Test Management” pane in “Integrated pane” Test
> Document the existence of the TestPlan plugin

- languages/en/administration-guide/system-administration/advanced-deployments.rst
Remove the incorrect remove nodejs instruction for installing realtime
> Correct realtime installation

- languages/en/developer-guide/ide-blackfire-configuration.rst
The path of phpunit.xml has changed, it is time to update it
> Update phpunit.xml path in IDE config documentation

- languages/en/administration-guide/system-administration/backend-workers.rst
This is part of story #14766: Have an import from jira structure
> Remove Jira feature flag

- languages/en/administration-guide/system-administration/backend-workers.rst
- Remove supported features from the missing features list
- Warn about public email addresses
> Update Jira documentation

- languages/en/administration-guide/system-administration/logs.rst
- languages/en/administration-guide/users-management/security/user-authentication/openidconnect.rst
- languages/en/deployment-guide/12.x.rst
- languages/en/user-guide/code-versioning/svn-plugin.rst
In addition to LDAP & OIDC support, inform about changes in 12.0
about handeling of OIDC users
> Inform about OIDC + LDAP

- languages/en/deploy.rst
- languages/en/user-guide/misc.rst
Part of [request #17155](https://tuleap.net/plugins/tracker/?aid=17155): Announce end of support of Internet Explorer
> Add a clear deadline for the end of support of Internet Explorer

- languages/en/_themes/tuleap_org/style/_doc.scss
- languages/en/dev.rst
- languages/en/developer-guide/project-background.rst
Copy paste of the existing is not enough, they need advice on webp
generation, and dominant color extraction.
Part of [story #16211](https://tuleap.net/plugins/tracker/?aid=16211): Set a header background image
> Explain to developer how to contribute a background image

- webpack.common.js
This custom plugin replaces the more generic fix-style-only-entries we used before migrating to Webpack 5.
Part of request #17195: Upgrade to Webpack 5
> Remove the JS empty file generated for the CSS entry point

- languages/en/developer-guide/tests/end-to-end.rst
If you launch first the cypress app, it will tell you that there is no
baseUrl or some cryptic message, because it cannot access
https://tuleap. You must first edit the hosts file and then open
cypress.
This changes the order of instructions in the doc.
> Edit etc hosts file before launching cypress app

- languages/en/user-guide/integration/rest/quick-start/update.rst
Complete the REST update artifact documentation with comment section
> Complete the REST update artifact documentation with comment section

- languages/en/install.rst
- languages/en/installation-guide/FAQ.rst
This commit adds an FAQ section from our experience on chat.tuleap.org.
This section will be expanded when we have recurrent questions.
> Adding an FAQ section

- languages/en/developer-guide/project-background.rst
Part of [story #18405](https://tuleap.net/plugins/tracker/?aid=18405): distinguish Features and P.I. that comes from a Program in a Team
> Dominant color of a project background is expected to be chosen with a minimum constrast ratio

- languages/en/developer-guide/quick-start/install-docker.rst
- languages/en/developer-guide/quick-start/run-tuleap.rst
Part of [request #18503](https://tuleap.net/plugins/tracker/?aid=18503): Setup reproducible build and dev environments
> Document using Nix to get a development environment

- languages/en/user-guide/trackers/usage/artifact-update.rst
This is part of story #18857 define any type of artifact as children
> Add documentation about new artifacts parent/child relationship

- languages/en/administration-guide/projects-management/export-import/import-format/trackers.rst
This is part of story #19253 import worklog as timetracking
> Add documentation about Tuleap timetracking format

- README.md
- default.nix
- package-lock.json
Expected and provided npm version is 7.x so the lockfile has been updated.
> Make possible to get all the needed tools to work on the documentation via Nix

- languages/en/developer-guide/front-end/vue.rst
Part of request #20573: Stop building condensed stylesheets
> Do not advise to build condensed stylesheets

- package-lock.json
- package.json
Vite 2.2 has a built-in watch mode, we do not need nodemon anymore 🎉
> Remove nodemon

- languages/en/deployment-guide/12.x.rst
- languages/en/user-guide/misc.rst
Following adr/0001-supported-browser-versions.md[1] in Tuleap
[1] https://tuleap.net/plugins/git/tuleap/tuleap/stable?a=blob&hb=master&f=adr%2F0001-supported-browser-versions.md
> Update supported browser list

- languages/en/user-guide/trackers/administration/configuration/semantics.rst
Now it has been implemented, let's document it.
part of: [story #20919](https://tuleap.net/plugins/tracker/?aid=20919) define progress of artifacts
> Document links count based semantic progress

- languages/en/user-guide/code-versioning/gitlab.rst
This is part of story #17183 close artifacts from commit messages
No screenshots are added here, we will wait until the whole UI part is
done to add them.
> Add base documenation about artifact closure feature

- languages/en/user-guide/code-versioning/git.rst
Part of [request #13356](https://tuleap.net/plugins/tracker/?aid=13356): Allow to change the default branch
> Add section about Git default branch

- languages/en/developer-guide/development-tools.rst
> Update cli-generate:artifacts documentation with nix environment

- languages/en/user-guide/misc.rst
There are no longer system to search in a tracker.
Now you can only make a reseach with the keyword and the id.
> Update search area doc to explain research with keyword

- languages/en/user-guide/integration/rest/api.rst
Part of [story #19731](https://tuleap.net/plugins/tracker/?aid=19731) manage steps in REST API: PUT /artifacts/:id
> Add an example on how to create/update a TTM step def field

- languages/en/deployment-guide/13.x.rst
Part of request #22669: Allow to disable HTTP->HTTPS redirection
> Add information about the removal of the sys_https_host setting

- languages/en/deploy.rst
part of request #22186 Run Tuleap with PHP 8.0
> Indicate that PHP 7.4 is not supported anymore

- languages/en/deployment-guide/13.x.rst
- languages/en/installation-guide/full-installation.rst
Part of [request #23451](https://tuleap.net/plugins/tracker/?aid=23451): Build the "additional" packages in the main build process
> Tuleap Community metadata repository are now signed

- languages/en/user-guide/integration/webhook.rst
Part of [request #24225](https://tuleap.net/plugins/tracker/?aid=24225) Send the artifact Id in webhook payload
> Update the artifact webhook payload with the artifact id

- languages/en/developer-guide/release.rst
Part of request #23465 Publish a project sidebar custom element
> Add instructions to release a JS lib

- .gitpod.yml
This provide linting & syntax highlighting for RestructuredText
> Add GitPod extension

- languages/en/deployment-guide/13.x.rst
- languages/en/installation-guide/docker-image.rst
Take the opportunity to add the missing env for DB Port.
> Update environment variable for 13.8

- languages/en/installation-guide/docker-image.rst
Make it clear what are the configuration pieces.
> Reorganize documentation about docker install

- languages/en/user-guide/code-versioning/git.rst
- languages/en/user-guide/trackers/administration/configuration/field-dependencies.rst
- languages/en/user-guide/trackers/usage/terminology.rst
part of story #26802 have smart commit with Tuleap Git
This adds documentation detailing what are the conditions needed to
close artifacts with Git commit message.
> Document how to close artifacts with Git commit message

- languages/en/_themes/tuleap_org/style/_doc.scss
Took the value of 'Ocean Turquoise' color in the TLP business colors to stay somewhat close to the color used in the RTD theme.
> Closes #994: Important is not rendered properly with docs.tuleap.org theme

- languages/en/user-guide/trackers/administration/configuration/semantics.rst
part of [story #26802](https://tuleap.net/plugins/tracker/?aid=26802) have smart commit with Tuleap Git
> Add a line in Done semantic usage for Git commits

- languages/en/user-guide/integration/rest/api.rst
"init" was not passed to fetch, so it was broken. I also moved around the functions.
You can try it by pasting the entire IIFE in your browser console.
> Fix the File attachment retrieval example

- languages/en/administration-guide/application-management/plugins/full-text-search.rst
- languages/en/installation-guide/install-plugins.rst
Part of [story #26771](https://tuleap.net/plugins/tracker/?aid=26771): Index artifact fields (REST + Switch to) on updated artifacts only
> Add a page into the administration guide about the FTS plugin

- languages/en/administration-guide/system-administration/logs.rst
- languages/en/user-guide/documents-and-files/doc.rst
- languages/en/user-guide/integration/onlyoffice.rst
Part of [story #28263][0]: edit office document stored in Document
[0]: https://tuleap.net/plugins/tracker/?aid=28263
> Documents can be edited in ONLYOFFICE integration

- languages/en/administration-guide/system-administration/advanced-deployments.rst
- languages/en/installation-guide/FAQ.rst
- languages/en/installation-guide/docker-image.rst
- languages/en/installation-guide/full-installation.rst
- languages/en/user-guide/trackers/usage/search-artifact.rst
Part of request #22660: Run Tuleap with MySQL 8.0
> Default install are now done using MySQL 8.0

- languages/en/user-guide/documents-and-files/doc.rst
Part of story #28273: create OnlyOffice documents
> Online office file can be created

- languages/en/administration-guide/application-management/plugins/full-text-search.rst
> Correct sudo command for fts_meilisearch plugin installation

- languages/en/administration-guide/users-management/security/user-authentication/authentication-flowchart.rst
- languages/en/conf.py
- languages/en/developer-guide/back-end.rst
- languages/en/developer-guide/back-end/flowcharts.rst
- poetry.lock
- pyproject.toml
- requirements.txt
While the code is the only source of truth to understand what is going on during the registration process, having a flowchart under the eyes will help to have a broader picture while developing features around the subject.
Like all documentation, it might become irrelevant some day, that is why a date is added on top to assert the "freshness" of the graph.
Part of [request #29614][0]: Invited users shouldn't be mandated to re-confirm their email
[0]: https://tuleap.net/plugins/tracker/?aid=29614
> Flowchart for user registration process

- languages/en/deployment-guide/14.x.rst
Part of [request #30733](https://tuleap.net/plugins/tracker/?aid=30733): Drop PHP 8.0
> Removal of PHP 8.0 packages

- languages/en/developer-guide/back-end.rst
- languages/en/developer-guide/back-end/keycloak.rst
Finding how to configure a keycloak server might be tedious, here is some documentation so that next contributors will have a better view of what is needed for a basic setup.
> Document keycloak server setup in dev environment

- languages/en/conf.py
- languages/en/developer-guide/back-end/keycloak.rst
- languages/en/developer-guide/back-end/tests.rst
- languages/en/user-guide/ci.rst
* Updated redirected links
* Added MySQL docs to the ignore list
* Modified Keycloack page to use an IP address in the documentation range
> Make `linkcheck` happy [W07]

- languages/en/installation-guide/full-installation.rst
Added the process to install Tuleap Enterpise Edition alongside the Community Edition
> Tuleap Enterprise Installation documented publicly

- languages/en/administration-guide/system-administration/mysql80-upgrade.rst
Some things prevented mysql from upgrading. Now fixed
> fixed some typos

- languages/en/installation-guide/full-installation.rst
Added EL9 documentation for 14.7 Release
> Documented EL9 support for TEE

- languages/en/administration-guide/system-administration/filtering-outbound-requests.rst
- languages/en/deployment-guide/14.x.rst
Part of [request #31580](https://tuleap.net/plugins/tracker/?aid=31580): Filter outbound HTTP requests
> Document SSRF protection and how to adjust the allow and deny lists

- languages/en/user-guide/project-admin.rst
- languages/en/user-guide/trackers/administration/tracker-creation.rst
* Add the information about the --visibility option in the CLI tool
* Add tables to inform about imported Jira system and custom fields at import
> Enhance Jira project import documentation

- languages/en/deploy.rst
Requests linked to the end of support changes:
- Reference Alias and Artifact Folder plugins: https://tuleap.net/plugins/tracker/?aid=30737
- Distributed SVN: https://tuleap.net/plugins/tracker/?aid=29998
- Supported browsers: https://tuleap.net/plugins/tracker/?aid=31952
- ForumML plugin: https://tuleap.net/plugins/tracker/?aid=33976
- Mailman: https://tuleap.net/plugins/tracker/?aid=33995
- CVS: https://tuleap.net/plugins/tracker/?aid=33997
> Update deprecations and end of support section

- languages/en/installation-guide/docker/images-configuration.rst
Précision au niveau du paramétrage par défaut
> Docker image configuration

- languages/en/installation-guide/docker/docker_compose.rst
Précision qu'il faut mettre au même endroit les deux fichiers créés
> modif docker compose

- languages/en/user-guide/code-versioning/git.rst
In goal to keep knowledge about how pre-receive git hook works in Tuleap, add documentation here and in developper guide.
> Pre-receive git hook documentation

- languages/en/user-guide/backlog.rst
Part of [story #35104][0]: Milestones below Backlog
[0]: https://tuleap.net/plugins/tracker/?aid=35104
> Document milestones in sidebar

- languages/en/installation-guide/step-by-step/install-packages-tee.rst
- languages/en/installation-guide/step-by-step/install-plugins.rst
- languages/en/user-guide/integration/webhook.rst
- languages/en/user-guide/trackers/administration/configuration-settings.rst
- languages/en/user-guide/trackers/administration/configuration/cce.rst
- languages/en/user-guide/tuleap-entreprise.rst
Part of [story #35093][0]: execute custom code as artifact post action
[0]: https://tuleap.net/plugins/tracker/?aid=35093
> Initiate doc for Tracker CCE

- languages/en/user-guide/trackers/administration/configuration/functions.rst
Part of [community #35093](https://tuleap.net/plugins/tracker/?aid=35093): execute custom code as artifact post action
> Add information about the security of Tuleap Functions

- languages/en/user-guide/trackers/usage/move-artifact.rst
This is part of request #34032 Move of artifacts should not depend on artifact deletion
> Add information about move artifact in tracker administration

- languages/en/user-guide/user/preferences.rst
Part of [request #37938][0] Add Korean translation
[0]: https://tuleap.net/plugins/tracker/?aid=37938
> Add Korean as available language

- languages/en/user-guide/trackers/administration/configuration/triggers.rst
This commit is the modification of triggers/hierarchy documentation. This commit is part of sla #96429.
> Doc(Fix) : Spelling correction

- languages/en/installation-guide/step-by-step/requirements.rst
System administrator can be tempted to install it and pre-configure it at this stage which can cause troubles later in the process.
> feat: Mention that MySQL installation will be guided on the requirements page

- languages/en/administration-guide/application-management/plugins/trackers.rst
- languages/en/user-guide/trackers/administration/configuration/delete-artifact.rst
This commit is here to prepare the page of artifacts deletion. A lot of tickets asked for some explanations. So this commit is here to answer their questions.
> Doc: Artifacts Deletion

- languages/en/deployment-guide/15.x.rst
- languages/en/user-guide/tql.rst
Part of [story #39019 Switch mode in Cross tracker search widget](https://tuleap.net/plugins/tracker/?aid=39019)
> doc: Add documentation about expert mode in XTS widget

- build-support/pinned-nixpkgs.nix
Main changes:
* Nodejs: 20.12.2 -> 20.15.1
* Python: 3.11.9 -> 3.12.4
> chore: request #39334 Update dev/build environment [W34 2024]

- languages/en/user-guide/tql.rst
Part of [story #39330 Choose on which tracker I perform my query](https://tuleap.net/plugins/tracker/?aid=39330)
> doc: Add FROM documentation

- languages/en/_pygments/lexer.py
- languages/en/user-guide/tql.rst
Part of [story #39685 Order artifact according to a field](https://tuleap.net/plugins/tracker/?aid=39685)
> doc: Add ORDER BY documentation

- build-support/pinned-nixpkgs.nix
> chore: request #40463 Update dev/build environment [W47 2024]

- Jenkinsfile-build-docs.tuleap.org
Part of enalean_internal #112083
> fix: Authenticate on Tailscale before signing docs.tuleap.org Docker image

- languages/en/user-guide/code-review/pullrequest.rst
Part of [story #38643 @ notifications in pull requests](https://tuleap.net/plugins/tracker/?aid=38643)
> doc: Document @ mention in Pull Request

- languages/en/deployment-guide/16.x.rst
Part of [story #41464 Convert non expert queries](https://tuleap.net/plugins/tracker/?aid=41464)
> doc: API breaking change caused by XTS

- languages/en/_themes/tuleap_org/header.html
- languages/en/administration-guide/system-administration/customisations.rst
- languages/en/conf.py
- languages/en/deployment-guide/12.x.rst
- languages/en/dev.rst
Source repo cannot be browsed without being authentiicated.
> fix: Fix and ignore links to Tuleap dev doc

- languages/en/user-guide/documents-and-files/artidoc.rst
We should mention that workflow should be disabled in order to use artidoc.
> Disable workflow for artidoc

- languages/en/deployment-guide/16.x.rst
Part of [story #41799 Have multiple queries per widget](https://tuleap.net/plugins/tracker/?aid=41799)
> doc: API breaking change caused by XTS in 16.5

- languages/en/administration-guide/system-administration/email-relay.rst
- languages/en/deployment-guide/16.x.rst
Part of request #42191 Replace laminas/laminas-mail with symfony/mailer
> chore: Adjust configuration related to SMTP mail relays

- build-support/pinned-nixpkgs.nix
Main changes:
* Node: 20.18.0 -> 22.14.0
> chore: request #42185 Update dev/build environment [W08 2025]

- languages/en/administration-guide/system-administration/email-relay.rst
- languages/en/deployment-guide/16.x.rst
Part of request #42191 Replace laminas/laminas-mail with symfony/mailer
> chore: Adjust configuration related to SMTP mail relays using TLS

- languages/en/deploy.rst
- languages/en/deployment-guide/16.x.rst
- languages/en/user-guide/misc.rst
part of [request #42610](https://tuleap.net/plugins/tracker/?aid=42610) Raise minimum supported browser versions to Chrome 127 and Firefox 128
> docs: Announce change of minimal supported browsers

- languages/en/deployment-guide/16.x.rst
part of story #42604 Update default templates with Cross Tracker Search
> docs: Mention templates dependency on XTS

- build-support/pinned-nixpkgs.nix
> chore: request #42960 Update dev/build environment [W18 2025]

- languages/en/installation-guide/step-by-step/prepare-database.rst
See [art #43352](https://tuleap.net/plugins/tracker/?tracker=140&aid=43352)
> chore: Inform administrators that we only work with 1 SQL mode

- build-support/pinned-nixpkgs.nix
Main changes:
* Node: 22.17.0 -> 22.19.0
* Python: 3.13.5 -> 3.13.7
> chore: request #44844 Update dev/build environment [W38 2025]
